version: '3.8'
services:
  client:
    build: ./
    container_name: react-frontend-template
    ports:
      - '3300:3300'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
